### ISSUE TITLE
Hitting Escape on a Select leaves prompt in a hung state

### ISSUE THREAD

**Issue by laggingreflex** [enquirer/enquirer#245]
When using a Select Prompt, and the user hits <kbd>Escape</kbd> key, it leaves the command prompt in kind of a "hung" state... it stops taking any input or displaying anything after it. 

Using the Select example from the docs, with a minor modifiction: 
```
prompt.run()
  .finally(() => {
    console.log('finally');
    setInterval(() => {
      console.log(new Date)
    }, 1000)
  })
```
In normal scenarios, after selecting an option, or even cancelling (Ctrl+C), it shows Date every second.

But if you hit escape, it "hangs" the console. The Date never appears, and you can't hit any keys either, not even Ctrl+C. 

Without the "finally" modification, it does not exit the program either... it just "hangs".

Tested on Windows 10, CMD.exe and PowerShell.

Edit: Seems to be a Windows only issue. It works fine on WSL-bash.

**Comment by jonschlinkert** [comment]
> Seems to be a Windows only issue. It works fine on WSL-bash.

Yeah, I was going to say that I could only reproduce this on Windows native shells. I'm not sure what the solution is for this, I'll look into it. PRs are welcome.

**Comment by laggingreflex** [comment]
It's affecting #273 too

**Comment by laggingreflex** [comment]
I think it's a readline issue: https://github.com/nodejs/node/issues/31762

Applying the workaround mentioned there (wrapping `rl.close` in setTimeout) fixes it

* **`lib/keypress.js`**
    ```js
    -rl.close()
    +setTimeout(() => rl.close())
    ```

**Comment by laggingreflex** [comment]
Simpler repro (using `prompt.cancel` , doesn't require hitting <kbd>Esc</kbd>): 

```js
const enquirer = new Enquirer();
enquirer.on('prompt', prompt => {
  prompt.cancel();
});

enquirer
  .prompt({ type: 'input', name: 'username', message: 'Username' })
  .then(({ username }) => console.log(username))
  .catch(err => console.error(err));
```

**Comment by laggingreflex** [comment]
The fix creates other problems... Any future prompts (after cancellation, using the fix) stop re-rendering properly.

**Comment by jonschlinkert** [comment]
> The fix creates other problems... Any future prompts (after cancellation, using the fix) stop re-rendering properly.

I might have an idea of how to fix this. I'll report back when I get a chance to test.

**Comment by ahmedkotb** [comment]
any update on this ?
another workaround is to remove listeners before cancellation
```js
process.removeAllListeners();
prompt.cancel()
```

**Comment by laggingreflex** [comment]
This seems to have been solved with Node v14.8.0. My original example is working as expected now.

**Comment by rivy** [comment]
Please re-open this...

This is still a problem for the vast majority of users. The issue seems to be a bug in `node` (affecting versions from Node-v10.2 thru Node-v14.6) [[1]](https://github.com/nodejs/node/issues/31762). Most users won't be on Node-v14.8 for months or years. It should be fixed with a workaround (preferably in code or at least documentation).

I'm using...

```javascript
const readline = require("readline");
// work-around for "hang" after 'enquirer' <ESCAPE>/cancel() on windows platforms; see <https://github.com/enquirer/enquirer/issues/245>
// * arises from "node" bug after Node-v10.2 thru Node-v14.6 => see <https://github.com/nodejs/node/issues/31762>
const readlineOldClose = readline.Interface.prototype.close;
readline.Interface.prototype.close = function () {
  this.terminal = false;
  readlineOldClose.call(this);
};

// ... then, run/use enquirer prompts
```

I haven't seen any negative side-effects from this as of yet.
